domain: elisawarner.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https:/elisawarner.github.io  # the base hostname and protocol for your site, e.g. http://example.com

theme: jekyll-theme-minimal

github:
  is_project_page: false
  is_user_page: true
  navbar: true

title: Elisa Warner
description: Austin, TX USA
logo: ./assets/img/logo.png
show_downloads: true